name: danger_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  json_annotation: ^3.1.1
  pedantic: ^1.9.0
  test: ^1.14.4
  json_serializable: ^3.5.1
  build_runner: ^1.11.5
  mockito: ^4.1.4
